# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-14 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_pic'),
        ('mall', '0005_auto_20180508_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metafield', jsonfield.fields.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pic', models.CharField(blank=True, max_length=500)),
                ('position', models.IntegerField(default=0)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='description_pic',
            field=models.CharField(blank=True, help_text='详情图', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='hot_pic',
            field=models.CharField(blank=True, help_text='热卖图', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='is_hot',
            field=models.CharField(blank=True, help_text='是否热卖', max_length=500),
        ),
    ]
