# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-15 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0006_auto_20190214_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_hot',
            field=models.BooleanField(default=False, help_text='是否热卖'),
        ),
    ]
