# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-18 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppic',
            name='pic',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
