# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-08 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180418_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='pic',
            field=models.CharField(blank=True, help_text='主图', max_length=500),
        ),
    ]
