# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 04:12
from __future__ import unicode_literals

import book.models
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metafield', jsonfield.fields.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('room', '订房')], default='room', max_length=255)),
                ('order_number', models.CharField(default=book.models.make_order_number, help_text='订单号', max_length=255)),
                ('price', models.FloatField(help_text='订单总价 单位元')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('refunding', '退款中'), ('refund', '已退款'), ('cancel', '已取消')], default='pending', max_length=255)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metafield', jsonfield.fields.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('pic', models.ImageField(upload_to='room_pic')),
                ('area', models.CharField(blank=True, help_text='面积', max_length=255)),
                ('bed_type', models.CharField(blank=True, help_text='床型', max_length=255)),
                ('window', models.CharField(blank=True, help_text='窗户', max_length=255)),
                ('bed_width', models.CharField(blank=True, help_text='床宽', max_length=255)),
                ('capacity', models.CharField(blank=True, help_text='入住人数', max_length=255)),
                ('floor', models.CharField(blank=True, help_text='所在楼层', max_length=255)),
                ('price', models.FloatField(default=100)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.Room'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop'),
        ),
    ]
