# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '__first__'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metafield', jsonfield.fields.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='room',
        ),
        migrations.AddField(
            model_name='order',
            name='arrive',
            field=models.CharField(blank=True, help_text='到店时间', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, help_text='姓名', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='mobile',
            field=models.CharField(blank=True, help_text='手机', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='remark',
            field=models.TextField(blank=True, help_text='备注'),
        ),
        migrations.AddField(
            model_name='order',
            name='use_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='use_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.CouponCode'),
        ),
        migrations.AddField(
            model_name='order',
            name='use_wx',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderroom',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Order'),
        ),
        migrations.AddField(
            model_name='orderroom',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.Room'),
        ),
    ]
