# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-03 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('room', '订房'), ('mall', '商城')], default='room', max_length=255),
        ),
    ]
