# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-12 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20180403_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='quantity',
            field=models.IntegerField(default=5),
        ),
    ]
