# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-27 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_auto_20180427_1520'),
        ('book', '0004_auto_20180418_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='order',
            name='use_coupon',
        ),
        migrations.RemoveField(
            model_name='orderroom',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderroom',
            name='room',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderRoom',
        ),
    ]
