# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-27 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_auto_20180418_1042'),
        ('book', '0005_auto_20180427_1520'),
        ('mall', '0004_auto_20180427_1520'),
        ('customer', '0002_auto_20180403_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metafield', jsonfield.fields.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('room', '订房'), ('mall', '商城')], default='room', max_length=255)),
                ('order_number', models.CharField(default=order.models.make_order_number, help_text='订单号', max_length=255)),
                ('price', models.FloatField(help_text='订单总价 单位元')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('refunding', '退款中'), ('refund', '已退款'), ('cancel', '已取消')], default='pending', max_length=255)),
                ('full_name', models.CharField(blank=True, help_text='姓名', max_length=255)),
                ('mobile', models.CharField(blank=True, help_text='手机', max_length=255)),
                ('remark', models.TextField(blank=True, help_text='备注')),
                ('use_balance', models.FloatField(default=0)),
                ('use_wx', models.FloatField(default=0)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('arrive', models.CharField(blank=True, help_text='到店时间', max_length=255)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop')),
                ('use_coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.CouponCode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metafield', jsonfield.fields.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mall.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metafield', jsonfield.fields.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.Room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
