# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-02 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0, help_text='订单总价 单位元'),
        ),
    ]
