# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-25 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20180602_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='use_point',
            field=models.FloatField(default=0),
        ),
    ]
